
[build.env]
passthrough = [
    "V8_FROM_SOURCE",
    "SCCACHE_ERROR_LOG",
    "SCCACHE_LOG",
    "SCCACHE_DIR",
    "SCCACHE_IDLE_TIMEOUT",
    "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=./third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++"
]

[target.aarch64-linux-android]
image = "test:latest"
